spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    producer:
      retries: 0
      acks: 1
      batch-size: 8192
      properties:
        linger:
          ms: 0
      buffer-memory: 16777216
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      default-topic: test.kafka.topic
    consumer:
      properties:
        group:
          id: defaultConsumerGroup
        session:
          timeout:
            ms: 12000
        request:
          timeout:
            ms: 18000
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 50
    listener:
      missing-topics-fatal: false
      type: batch